/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/health` | `/leoTrack/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/history` | `/leoTrack/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack` | `/leoTrack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/map` | `/leoTrack/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/result` | `/leoTrack/result`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leoTrack/health` | `/leoTrack/health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leoTrack/history` | `/leoTrack/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leoTrack` | `/leoTrack`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leoTrack/map` | `/leoTrack/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leoTrack/result` | `/leoTrack/result`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leoTrack/health${`?${string}` | `#${string}` | ''}` | `/leoTrack/health${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leoTrack/history${`?${string}` | `#${string}` | ''}` | `/leoTrack/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leoTrack${`?${string}` | `#${string}` | ''}` | `/leoTrack${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leoTrack/map${`?${string}` | `#${string}` | ''}` | `/leoTrack/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leoTrack/result${`?${string}` | `#${string}` | ''}` | `/leoTrack/result${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/health` | `/leoTrack/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/history` | `/leoTrack/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack` | `/leoTrack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/map` | `/leoTrack/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leoTrack/result` | `/leoTrack/result`; params?: Router.UnknownInputParams; };
    }
  }
}
